---
- name: Configure the enterprise domain controller
  hosts: domain_controllers
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: "{{ hostvars[inventory_hostname].ansible_port | default(5986) }}"
  roles:
    - role: adds
...
